//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Model.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stu_City
    {
        public int ID { get; set; }
        public string CityName { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> StateID { get; set; }
    
        public virtual Stu_Country Stu_Country { get; set; }
        public virtual Stu_State Stu_State { get; set; }
    }
}
