//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement_331.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemDetails
    {
        public int ID { get; set; }
        public string ITEM_NAME { get; set; }
        public Nullable<int> ITEM_QTY { get; set; }
        public Nullable<decimal> ITEM_PRICE { get; set; }
        public Nullable<int> ORDERID { get; set; }
    
        public virtual UserOrder UserOrder { get; set; }
    }
}
