//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement_331.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableCouponCodeMaster
    {
        public int CouponICoded { get; set; }
        public string Code { get; set; }
        public Nullable<int> CouponType { get; set; }
        public Nullable<decimal> Flat_Amount { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> UsageLimit { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual CouponType CouponType1 { get; set; }
    }
}
