//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement_331.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableItemMaster
    {
        public int ItemID { get; set; }
        public string Item_Name { get; set; }
        public Nullable<decimal> Item_Amount { get; set; }
    }
}
