//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement_331.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserOrder()
        {
            this.ItemDetails = new HashSet<ItemDetails>();
        }
    
        public int OrderId { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> Total_Qty { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AFTER_GST { get; set; }
        public string PROMO { get; set; }
        public Nullable<decimal> TOTAL_PAYABLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemDetails> ItemDetails { get; set; }
        public virtual User User { get; set; }
    }
}
